version: "3.7"
services:
  api:
    build: .
    ports:
      - 4000:4000
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
